### ISSUE TITLE
Do we need multi-release jar files?

### ISSUE THREAD

**Issue by amatiushkin** [intuit/Traverser#11]
More specifically (this [feature](https://openjdk.java.net/jeps/238)). It could be a practical way forward to provide one artifact which covers future Java versions (java 9+).

**Comment by shravyags** [comment]
@amatiushkin I would like to work on this as a first time contributor to this repo. Could you please assign this to me?

**Comment by shravyags** [comment]
@amatiushkin should I do research if we need multi-release jar files initially or should I directly start thinking in perspective on how to add this feature implementation-wise?

**Comment by amatiushkin** [comment]
@shravyags I would suggest to research if this is needed.

For example to support for LTS version of java, will it be the right approach going forward or not.
It would be good to collect actual experience from other projects and only add if this looks as industry-wide practice.

**Comment by shravyags** [comment]
@amatiushkin Since I am new to this repo, I would like to take your suggestion on how to go about it. 

I did some research on how to add multi-release jar files into repo, what are cons/disadvantages of having multi-release jar over having multiple jars. Some of the major problems people face that I gathered from blog posts and website are - 

1. IDE and build tool must be configured appropriately to allow easy work on the source files with the same fully-qualified name that are compiled against different Java versions
2. You need to keep multiple variants of the same source file in sync, so that they keep the same public API
3. Testing gets more complicated because you might end up writing tests that only run or pass on specific JVM versions
4. Multi-release JARs can contain bytecode for different Java versions and JVMs from version 9 on can shadow version-unspecific classes with version-specific ones. This allows you to use new APIs if the JAR is executed on a JVM that supports them. They don't really help if you want to use new language features.
5. Generally speaking, creating multi-release JARs complicates the entire development process from IDE and build tool configuration, to design, code, and tests. Only use this feature if you get something in return.

Let me know what you think about going ahead and implementing multi-release jar files.

**Comment by amatiushkin** [comment]
@shravyags Thank you for taking time to research this topic.  

It does sound that supporting multi-release JARs will require more effort and future maintenance which goes beyond project configuration alone.

Have you noticed/discovered use cases where it does make sense to use this feature in the field?

**Comment by shravyags** [comment]
Yes, it does makes sense to use it for the following reason but comes with baggage/above mentioned problems.

Some of the 'why to use' reasons were - 

1. Java 9 enhanced the JAR file format which can contain multiple Java-release-specific versions of our class files to coexist in a single archive. 
2. Using this feature, we can upgrade our application/library to new version of Java without forcing the users to upgrade to the same Java version.
3. MRJAR leave the original class untouched and instead create a new version using the new JDK and package them together. At runtime, the JVM (version 9 or above) will call any one of these two versions giving more preference to the highest version that the JVM supports.

It has both advantages and disadvantages. So wanted your suggestion.

**Comment by amatiushkin** [comment]
@shravyags

I am happy with current level of details. The real decision will be made when traverser is ported to java8+ version.

Thank you for taking time to research this topic. It greatly helps.
